// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCk-oXC9Ry5pv_JCTCc0QrhEFMrPXTQMA',
    appId: '1:437535331031:web:ce73de9bc92ff0a0ab5692',
    messagingSenderId: '437535331031',
    projectId: 'messapp-733e9',
    authDomain: 'messapp-733e9.firebaseapp.com',
    storageBucket: 'messapp-733e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-BEZOlEIhTdtf8MVod72cQxoUod97nw',
    appId: '1:437535331031:android:1a453e284e5a3341ab5692',
    messagingSenderId: '437535331031',
    projectId: 'messapp-733e9',
    storageBucket: 'messapp-733e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvzoj-7ie4ftkiCrHPKgy886LWqw7Wv3Y',
    appId: '1:437535331031:ios:cb67e24527cc9d89ab5692',
    messagingSenderId: '437535331031',
    projectId: 'messapp-733e9',
    storageBucket: 'messapp-733e9.appspot.com',
    iosClientId: '437535331031-8sp2mrsc5padn8tmpq57ifufpi7irgiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.messApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCk-oXC9Ry5pv_JCTCc0QrhEFMrPXTQMA',
    appId: '1:437535331031:web:c003dc80ec6c185cab5692',
    messagingSenderId: '437535331031',
    projectId: 'messapp-733e9',
    authDomain: 'messapp-733e9.firebaseapp.com',
    storageBucket: 'messapp-733e9.appspot.com',
  );
}
